Use existing sm in tests
terraform-ibm-modules/terraform-ibm-rag-sample-da pull request #83
Opened 2024-05-21 13:44 UTC by rajatagarwal-ibm

### Description

Use permanent SM instance account for tests

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-21 13:44 UTC, rajatagarwal-ibm commented
/run pipeline

2024-05-23 11:48 UTC, ocofaigh commented on tests/scripts/pre-validation.sh
> +SECRETS_MANAGER_GUID="79c6d411-c18f-4670-b009-b0044a238667"
can you pull this from the permanent resource yaml instead of hard coding it incase it ever changes

2024-05-23 11:49 UTC, ocofaigh requested changes
1 comment

2024-05-23 12:04 UTC, rajatagarwal-ibm commented
/run pipeline

2024-05-23 20:02 UTC, ocofaigh commented on tests/scripts/pre-validation.sh
> +SECRETS_MANAGER_GUID=$(curl -X GET --retry 3 -fLsS https://raw.githubusercontent.com/terraform-ibm-modules/common-dev-assets/main/common-go-assets/common-permanent-resources.yaml | yq e '.secretsMana
no need to do this either - common-dev-assets will be locally available in the git submodule - so just pull it locally

2024-05-27 13:31 UTC, rajatagarwal-ibm commented
/run pipeline

2024-05-27 14:00 UTC, ocofaigh commented on tests/scripts/pre-validation.sh
> +    terraform apply -input=false -auto-approve -var-file=${TF_VARS_FILE} || exit 1
no need to indent here

2024-05-27 14:22 UTC, rajatagarwal-ibm commented
/run pipeline

2024-05-27 14:29 UTC, ocofaigh approved these changes

2024-05-27 14:51 UTC, rajatagarwal-ibm commented
/run pipeline

2024-05-28 10:23 UTC, vburckhardt approved these changes

2024-05-28 10:23 UTC, merged

2024-05-31 19:11 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.9.5 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/releases/tag/v1.9.5)
- `v1.9.5`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: